### PR TITLE
Bug 1522341 - Implement new field for indicating if a bug is a task, enhancement, or defect

### PR DESCRIPTION
**Pull request by kyoshino**
Add new **Type** field to bugs. Just like other bug fields, it will appear everywhere including the search page and bug lists, and are also available via the API. The field values, defaulted to **defect**, **enhancement** and **task** (these are still subject to change), can be edited by Bugzilla admin. The default type per component can also be changed on the Edit Component page. See my [UX spec](https://drive.google.com/file/d/1l596C3yyE1if19SZqnDhYo8Wa2kSGget/view) for details.

The implementation is mostly a copy of the Severity field. While the API field and Quick Search keyword is `type`, the internal field name remains `bug_type` given that `type` is a SQL reserved word.

## Bugzilla link

[Bug 1522341 - Implement new field for indicating if a bug is a task, enhancement, or defect](https://bugzilla.mozilla.org/show_bug.cgi?id=1522341)

### CODE REVIEW

**Comment by kyoshino** [comment]
Labelling as **blocked** since the types are not finalized yet.

**Comment by kyoshino** [comment]
This PR needs a rebase after the schema change #1092 and ES removal #1102 are merged.

**Comment by kyoshino** [comment]
Available for testing on https://bugzilla-dev.allizom.org/

**Comment by nt1m** [comment]
@kyoshino While this is nice, isn't this redundant with the "Importance" field ? Maybe that field could be simplified instead.

**Comment by kyoshino** [comment]
@nt1m The [enhancement severity is going away](https://bugzilla.mozilla.org/show_bug.cgi?id=1524738) in favour of the new bug type field’s enhancement type. Besides, my [ongoing analysis](https://docs.google.com/document/d/1Uoq7XtSb17mfmpg-VED8bl-lfqU9Xl4VVv9AsRYV8Dw/edit) finds many redundancy and inconsistency issues on various bug fields, which have to be solved in any way.

**Comment by kyoshino** [comment]
Do not merge yet until we get a green light.

**Comment by kyoshino** [comment]
We gotta ship it later this week.

**Pull request merged**
