### PR TITLE
Bug 1878813 - Make search pages and enter/show bug pages responsive

### PR DESCRIPTION
**Pull request by kyoshino**
[Bug 1878813 - Make search pages and enter/show bug pages responsive](https://bugzilla.mozilla.org/show_bug.cgi?id=1878813)

This makes the following pages responsive for a better experience on mobile:

- Simple search
- Advanced search
- Search results
- Enter bug
- Show bug

The changes for the new attachment overlay are not included. I’ll work on it once #2186 is merged.

### CODE REVIEW

**Comment by dklawren** [comment]
> When editing a bug from show bug, the tracking flags are displayed twice. The second portion in Details shows each tracking flag (custom field as a text input. 

Scratch this part. This is something going on with my local environment. The other two issues are still valid.

**Comment by kyoshino** [comment]
Thanks @dklawren! I’ve fixed the private bug banner and attachment list, and optimized the attachment overlay.

**Review by dklawren — CHANGES_REQUESTED** [review]
The two items before are looking great. Unfortunately minor issue is now occurring:

image
image

After the above fix, we should be good to go.

**Comment by kyoshino** [comment]
Oops, fixed!

**Review by dklawren — APPROVED** [review]
Nice work!

**Pull request merged**
