### PR TITLE
Bug 602313 - Allow creation of attachments by pasting an image from clipboard, as well as by drag-and-dropping a file from desktop

### PR DESCRIPTION
**Pull request by kyoshino**
## Description

* Enhance the attachment uploader with minimum backend changes (Base64 input support like API)
* Refactor the JavaScript code, reducing the usage of inline scripts and event handlers

## Bug

[Bug 602313 - Allow creation of attachments by pasting an image from clipboard, as well as by drag-and-dropping a file from desktop](https://bugzilla.mozilla.org/show_bug.cgi?id=602313)

## New features & enhancements

* Allow to drag & drop a file
* Allow to paste an image
* Show a thumbnail for image and plaintext files
* Put the text area in front so users don’t have to click a link to show it
* Detect and display the Content Type client-side so users can correct it at once if wrong
* Detect GitHub PR links to insert the description and check “take bug”
* Detect pasted patches
* Warn oversized files (from #607)

## Scenarios

* Browse an image file
* Browse a regular file (e.g. PDF)
* Browse an oversized file (e.g. ZIP)
* Browse a patch
* Drag & Drop an image file
* Drag & Drop a regular file (e.g. PDF)
* Drag & Drop an oversized file (e.g. ZIP)
* Drag & Drop a patch
* Drag & Drop a GitHub link
* Paste a patch
* Paste a GitHub link
* Paste a regular string (e.g. JavaScript)
* Paste an image file

## Screenshots
screen shot 2018-06-25 at 20 15 00
screen shot 2018-06-25 at 20 16 10
screen shot 2018-06-26 at 09 05 42
screen shot 2018-06-25 at 20 16 24

### CODE REVIEW

**Comment by kyoshino** [comment]
I don't know why I still see failures in the Selenium test results. Both tests are attaching a patch, and the `ispatch` checkbox should be checked. It works when testing manually. Perhaps part of the script is not running while testing? 🤔 

```
#   Failed test 'get_value, //input[@name="ispatch"], 'on''
#   at test_flags.t line 428.
#          got: 'off'
#     expected: 'on'
```

**Comment by dylanwh** [comment]
> I don't know why I still see failures in the Selenium test results. Both tests are attaching a patch, and the ispatch checkbox should be checked. It works when testing manually. Perhaps part of the script is not running while testing? 🤔
I bet the code doesn't work in the (ancient) firefox we run in selenium. You could disable/comment out that test.

**Comment by dylanwh** [comment]
@kyoshino since this still says in progress... would you like it merged into bugzilla-dev?

**Comment by kyoshino** [comment]
Yes please, if possible. I'll test all the written scenarios with all the supported browsers and mobile. Already tested with Firefox and Chrome though.

**Comment by dylanwh** [comment]
Filed a bug for dev deployment, probably it'll go out tomorrow. 
[Bug 1471380](https://bugzilla.mozilla.org/show_bug.cgi?id=1471380)

Also will have a staging/prod push (#628, bug not filed yet)

**Comment by kyoshino** [comment]
I’m cancelling this PR in favour of the new attachment overlay on the main bug page. These enhancements I mentioned before are all great, but this doesn’t solve key UX issues: people still have to find an obscure Attach File link to navigate to a separate page, and multiple files cannot be uploaded. I will reuse part of this code to start working on the overlay UI as seen on Slack.

**Comment by dylanwh** [comment]
I'd still like to merge this, as it is pleasant enough as-is. Is that okay? @kyoshino

**Comment by kyoshino** [comment]
Ah oh, then let me test with other browsers than Firefox and Chrome.

**Comment by kyoshino** [comment]
Solved a conflict with #676 on the `img-src` CSP directive line. Will test this today, really.

**Comment by dylanwh** [comment]
@kyoshino How about we release this at the same time as markdown?

**Comment by kyoshino** [comment]
Suddenly my VM corrupted this morning but it's probably a good time to test with a fresh machine. Let's ship it and Markdown this week!

**Pull request merged**
