### PR TITLE
Bug 1366143 - Fix alignment of select boxes

### PR DESCRIPTION
**Pull request by kyoshino**
Probably a better approach than #142.

### CODE REVIEW

**Comment by kyoshino** [comment]
Improved style:
screen-shot-2017-07-13-at-10 26 09
screen-shot-2017-07-13-at-10 30 08

**Comment by floatingatoll** [comment]
Screenshot comments:

`mbered`'s input field is very badly misaligned.

`Summary`'s input field is slightly misaligned, as well as all four
left-column selectors under Status.

**Comment by floatingatoll** [comment]
Also, the non-select input fields are aligned incorrectly vs. the select
input fields in the `ation` block.

**Comment by floatingatoll** [comment]
Also, the `Search` and `Mark as Duplicate` buttons are differently-aligned in their respective rows, vs the items to their left.

**Comment by kyoshino** [comment]
Fixed the alignment issues. Probably not perfect but it looks better now. Since I'd like to overhaul the modal bug UI, I don't want to touch the minor layout glitches any more :wink:

**Comment by floatingatoll** [comment]
A screenshot showing the repairs would be essential here for confirming them. I'm happy to accept some amount of "not great" as long as it's not *introduced* by this work.

**Comment by kyoshino** [comment]
Updated screenshots:
screen shot 2017-07-14 at 08 46 53
screen shot 2017-07-14 at 08 46 32

**Comment by dylanwh** [comment]
I'm checking the attachments page, which is the source of the original bug report

**Comment by dylanwh** [comment]
Considering the noise about autosize, I'm putting this off until next week

**Pull request merged**
