### PR TITLE
Bug 1816611 - Add links to download Firefox Beta and Nightly to the index page

### PR DESCRIPTION
**Pull request by globau**
- add links to download Firefox Beta and Nightly to /home
- modernise the layout of the links to support, connect, webcompat
- remove most items duplicated in the page header (search, docs, preferences, etc)
- mention that "other Mozilla products" are tracked here

### CODE REVIEW

**Comment by globau** [comment]
Screenshots:  [Unauthenticated](https://bug1816611.bmoattachments.org/attachment.cgi?id=9318655), [authenticated](https://bug1816611.bmoattachments.org/attachment.cgi?id=9318656)

**Review by dklawren — CHANGES_REQUESTED** [review]
We need different icons for dark mode as they are barely visible.
image

**Review by dklawren — COMMENTED** [review]
The rest looks good to me.

**Review by dklawren — APPROVED** [review]
Looks great! r=dkl

**Pull request merged**
