### PR TITLE
Bug 1209148 - Stop using short-life token for internal REST API auth, which is problematic especially on My Dashboard, and rely on login cookie instead

### PR DESCRIPTION
**Pull request by kyoshino**
## Description

* Internal `Bugzilla_api_token` is problematic and redundant. The existing login cookie can be used instead for API auth.
* Public `Bugzilla_token` is a different thing, and it should not be affected by this change.

## Bug

[Bug 1209148 - Stop using short-life token for internal REST API auth, which is problematic especially on My Dashboard, and rely on login cookie instead](https://bugzilla.mozilla.org/show_bug.cgi?id=1209148)

### CODE REVIEW

**Comment by kyoshino** [comment]
So... I tried, and looks like this is working. The real culprit is `$login_cookie = ''` in `Cookie.pm`.

**Comment by kyoshino** [comment]
`/rest/bug/attachment/${id}` I want to use for [Bug 1496207](https://bugzilla.mozilla.org/show_bug.cgi?id=1496207) doesn't work when the `Bugzilla_api_token` param is set in the query string. It's a PUT request. I would like to this PR get reviewed and merged so the problem should be gone.

> The requested method 'Bugzilla::Attachment::set_Bugzilla_api_token' was not found.

**Comment by kyoshino** [comment]
I just encountered the invalid token error on My Dashboard  :neutral_face:

invalid token error

**Comment by kyoshino** [comment]
This is basically a removal so no code review needed. Just want to make sure this works as expected and no security issues introduced.

**Comment by floatingatoll** [comment]
@kyoshino What circumstances can activate this code block today?

https://github.com/mozilla-bteam/bmo/pull/782/files#diff-e432c9f5510c145bfbb4a9eb373e5209L107
```
            # forbid logging in with a cookie if only api-keys are allowed
            if (i_am_webservice() && !$is_internal) {
```

**Comment by kyoshino** [comment]
I meant: no review for *newly added* code is required...

**Comment by floatingatoll** [comment]
(I'd planned to ask that question in any case, but thank you for clarifying all the same!)

**Comment by kyoshino** [comment]
Maybe @floatingatoll is right. That particular part should not be removed after all. I'm reverting it and only remove the `is_internal` check. But hmm, what happens then?

**Comment by dylanwh** [comment]
I think api_key only might just have been for preventing CSRF attacks, which is now mitigated by SameSite cookies.

**Comment by kyoshino** [comment]
So can we remove the `api_key_only` setting also?

**Comment by kyoshino** [comment]
This PR needs to be updated once #917 is merged.

**Pull request closed without merging**
