### PR TITLE
Bug 1427621 - Support uploading multiple attachments from new-bug

### PR DESCRIPTION
**Pull request by SebastinSanty**

### CODE REVIEW

**Comment by SebastinSanty** [comment]
This breaks the normal attachments, I'm fixing that. Otherwise, on the new-bug side, it is perfectly working. The design can be commented upon. r? @dylanwh @kyoshino

**Comment by dylanwh** [comment]
Yep, you should change all the places where get_content_type is called.

**Comment by dylanwh** [comment]
@SebastinSanty there needs to a bug on file for this -- then I'll land it.

**Comment by dylanwh** [comment]
@SebastinSanty need to resolve the conflict, then I'll approve and land.

**Pull request closed without merging**
