### PR TITLE
Minor fix: Remove deprecation warning due to `include` in Ansible

### PR DESCRIPTION
**Pull request by SebastinSanty**

### CODE REVIEW

**Comment by kyoshino** [comment]
Now I get the following error when running `vagrant rsync && vagrant provision --provision-with update`:

```
    db: Running ansible-playbook...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/vagrant_support/update.yml': line 18, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - include_tasks: checksetup.yml
      ^ here


The error appears to have been in '/vagrant/vagrant_support/update.yml': line 18, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - include_tasks: checksetup.yml
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Did I miss something?

**Comment by kyoshino** [comment]
Will figure out how.

**Comment by floatingatoll** [comment]
https://www.jeffgeerling.com/blog/2016/require-minimum-ansible-version-your-playbook may also be of interest.

**Comment by kyoshino** [comment]
Okay, I just logged into each server:

```sh
$ vagrant ssh db
$ vagrant ssh web
```

And simply run:

```sh
$ sudo yum update -y ansible
```

That's it!

**Pull request merged**
