### PR TITLE
Bug 1421401 - Implement emoji comment reactions

### PR DESCRIPTION
**Pull request by kyoshino**
[Bug 1421401 - Implement emoji comment reactions](https://bugzilla.mozilla.org/show_bug.cgi?id=1421401)

- Implement emoji reactions like GitHub issue comments; a simple, familiar UX
- Enabled by default; can be disabled with an admin param
- The relevant code is part of the Bugzilla core as glob said, but the UI is still under the BugModal extension
- Changes are made realtime via a new API method; no bug submission needed
- Reacted user names will also be retrieved with a new API method when hovering a reaction button and displayed in a tooltip
- Add a new database table
- Reactions are not recorded as bug activities as per the task details
- Add Selenium and REST API tests
- Update the API document

### CODE REVIEW

**Review by dklawren — COMMENTED** [review]
image

Styling nit-pick: When collapsing the comments, the reactions should also not be visible IMO. As it is now, they are visible and right up against the comment header.

**Review by dklawren — CHANGES_REQUESTED** [review]
Everything else looks great and works well in my testing. Just the display change mentioned and then we can finish this up.

**Comment by kyoshino** [comment]
Thanks @dklawren! Fixed the style on collapsed comments 😅 The reactions should be hidden when collapsed, for sure.

**Review by dklawren — APPROVED** [review]
LGTM. r=dkl

Can you file a separate PR with just the Schema changes?

**Comment by kyoshino** [comment]
Will do.

**Pull request merged**
