### PR TITLE
Bug 1331305 - Auto resize the height of textarea of "add comment"

### PR DESCRIPTION
**Pull request by KuoE0**
[Bug 1331305 - Auto resize the height of textarea of "add comment"](https://bugzilla.mozilla.org/show_bug.cgi?id=1331305)

Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1331305.

### CODE REVIEW

**Comment by wlach** [comment]
This is just a drive-by comment, but it seems as if with your patch the text area could grow arbitrarily large, which I'm not sure is what we want.

I would define a maximum height for the textarea that would not be exceeded. This is how github comments seem to work.

**Comment by KuoE0** [comment]
I updated the patch with setting 80% height of the viewport as the max height.

**Comment by KuoE0** [comment]
Hi @dylanwh, I cannot watch this video. It shows "This video is unavailable." Can you check that? Thx!

**Comment by wlach** [comment]
Browsing on the web, it seems like this is not a simple problem.

http://stackoverflow.com/questions/454202/creating-a-textarea-with-auto-resize
http://stackoverflow.com/questions/19170083/automatically-resize-text-area-based-on-content

Could you perhaps just use http://www.jacklmoore.com/autosize/ ?

**Pull request closed without merging**
