### PR TITLE
Bug 1543700 - Reimplememt Custom Search UI on Advanced Search page

### PR DESCRIPTION
**Pull request by kyoshino**
Allow to flexibly add, remove and rearrange Custom Search criteria with a click on a button or drag & drop of a row or group. You cannot “undo” with the current UI when you made any mistake, so this change makes release managers and everyone’s life much easier.

bug1543700

## Bugzilla link

[Bug 1543700 - Reimplememt Custom Search UI on Advanced Search page](https://bugzilla.mozilla.org/show_bug.cgi?id=1543700)

### CODE REVIEW

**Comment by kyoshino** [comment]
Whew, I think the code is now ready for review.

**Comment by dylanwh** [comment]
@kyoshino does this conflict with the light/dark re-skin?

**Comment by kyoshino** [comment]
Yes, so if this can be merged now, I’ll update the other. Otherwise I’ll update this later on to match Dark Mode.

**Comment by kyoshino** [comment]
Updated this and several other PRs for the new skin.

**Pull request merged**
