### PR TITLE
Bug 1873826 - Avoid hiding scrollbar when opening drop down menu.

### PR DESCRIPTION
**Pull request by arai-a**
Instead of suppressing scroll by hiding scroll bar, let the drop down menu follow the scroll,
so that the page content doesn't shift by hiding/showing scrollbar for each click.

### CODE REVIEW

**Comment by arai-a** [comment]
`3_test_net_attachments.t` intermittently fails even without the patch.
so I'll leave it for other bug.

**Comment by dklawren** [comment]
> `3_test_net_attachments.t` intermittently fails even without the patch. so I'll leave it for other bug.

I am running it again and will probably pass the second time around. I am looking at it as a timing issue and will hopefully fix it for good soon.

**Comment by dklawren** [comment]
I will let @kyoshino review this one

**Comment by kyoshino** [comment]
@arai-a Thanks for the heads-up! I thought there would be a simpler solution to this, and [found this article](https://blog.mayank.co/is-dialog-enough) introducing [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter). So we just need this:

```css
html {
  scrollbar-gutter: stable both-edges;
}
```

**Review by kyoshino — CHANGES_REQUESTED** [review]
@arai-a Thanks for the heads-up! I thought there would be a simpler solution to this, and [found this article](https://blog.mayank.co/is-dialog-enough) introducing [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter). So we just need this probably in [`global.css`](https://github.com/mozilla-bteam/bmo/blob/master/skins/standard/global.css#L340):

```css
html {
  scrollbar-gutter: stable both-edges;
}
```

**Pull request closed without merging**
