### PR TITLE
Make bug modal usable at less than 900px

### PR DESCRIPTION
**Pull request by dylanwh**
Re-did this PR to focus on the sub-900 widths on bug modal

### CODE REVIEW

**Comment by dylanwh** [comment]
@purelogiq what about https://bugzilla-dev.allizom.org/show_bug.cgi?id=900 at a 800px width?

**Comment by purelogiq** [comment]
@dylanwh At exactly 800px things look "fine" but the tables in the people and status column are stuck. This is noticble when you reduce the width even further.

At 800px
800e

At 720px


At less than 600, clipping is based on the length of the text:
800l

**Comment by dylanwh** [comment]
I think you have cached CSS, can you do a shift-reload?

**Comment by dylanwh** [comment]
At 800 it looks like this for me, which I consider "good enough":

screen shot 2018-01-10 at 14 33 24

**Comment by purelogiq** [comment]
@dylanwh I tested in a private windows (which I assume doesn't cache). Your 800px and my 800px look about the same, no?

**Comment by dylanwh** [comment]
Ah, yes, you're right. Anyway, an r+ is an r+. Thanks!

**Pull request merged**
