### PR TITLE
Fix bug #1370378 - Add Phabricator Extension enabled flag to instantly toggle off all Phabricator syncing. r?dkl

### PR DESCRIPTION
**Pull request by darkwing**
https://bugzilla.mozilla.org/show_bug.cgi?id=1370378

### CODE REVIEW

**Comment by floatingatoll** [comment]
As this is a single-commit pull requests, would you mind terribly amending the commit message to "Bug 1370378 - Add ..."?

**Comment by darkwing** [comment]
Updated!

**Comment by dklawren** [comment]
David, looks good so far. We will also need some code added to extensions/PhabBugz/bin/update_project_members.pl (around line 30 or 31) that exits early if !Bugzilla->params->{phabricator_enabled}. Should be r+ after that.

**Comment by darkwing** [comment]
Thanks @dklawren !  Updaed!

**Pull request merged**
