### PR TITLE
Bug 1425119 - Release new-bug interface

### PR DESCRIPTION
**Pull request by SebastinSanty**
This PR discusses everything that needs to be done, in order to release new-bug interface to the public.

### CODE REVIEW

**Comment by dylanwh** [comment]
This needs a bug to land.

**Comment by SebastinSanty** [comment]
@dylanwh I have updated the PR, does it look good?

**Comment by dylanwh** [comment]
oh yeah, probably split on /\s*,\s*/ rather than /, /

**Comment by SebastinSanty** [comment]
Yep, a better solution. BTW would having a beta tag be better? We can have a feedback from users.

**Pull request merged**
