### PR TITLE
Bug 1472565 - Allow to instantly search recently visited bugs, ID/aliases, keywords, components in the quick search bar

### PR DESCRIPTION
**Pull request by kyoshino**
## Description

Enhance the quick search bar on the global navigation so it will be able to show/filter the user’s recently visited bugs, saved searches, components and keywords as well as [possible duplicates](https://bmo.readthedocs.io/en/latest/api/core/v1/bug.html#possible-duplicates) as you type. See [this screenshot](https://twitter.com/BugzillaUX/status/1013919072252096512) in action.

## Bug

[Bug 1472565 - Allow to instantly search recently visited bugs, possible duplicates, keywords, components in the quick search bar](https://bugzilla.mozilla.org/show_bug.cgi?id=1472565)

### CODE REVIEW

**Comment by kyoshino** [comment]
Again, the Selenium tests are struggling 😕

**Comment by kyoshino** [comment]
@dylanwh we still have to fix the tests by [upgrading Firefox](https://github.com/mozilla-bteam/bmo-systems/pull/8).

**Comment by dylanwh** [comment]
There is no easy path forward for the selenium tests. How about we just remove them?
@dklawren

**Comment by dklawren** [comment]
> There is no easy path forward for the selenium tests. How about we just remove them?
> @dklawren

I am hesitant to just remove selenium tests wholesale as they have been good for us in the past to catch random issues with new features even if the tests are not written to explicitly test those features. Sometimes new code will cause one or more of the standard pages to not load properly which are caught by the UI tests. Can we not just fix bug them by upgrading the dependencies as @kyoshino has made a PR for?

**Comment by dylanwh** [comment]
It's not possible to use Test::Selenium with modern selenium, and we're stuck on firefox 47 there. :-/

**Comment by dklawren** [comment]
> It's not possible to use Test::Selenium with modern selenium, and we're stuck on firefox 47 there. :-/

Or we convert our current scripts to Webdriver which I have wanted to do for quite some time but it is not a trivial undertaking.

**Comment by kyoshino** [comment]
I’m also worried that removing Selenium tests may potentially lead to security holes. I was constantly adding tests while contributing to [Bedrock](https://github.com/mozilla/bedrock) so would rather like to add/see more (modernized) tests in Bugzilla too.

**Comment by kyoshino** [comment]
I wanted to ship this earlier (with Bugzilla 6.0) so implemented a workaround for test failures on Firefox 47.

**Comment by kyoshino** [comment]
I’ll remove the Firefox 47 workaround once #1273 is merged.

**Pull request closed without merging**
