### PR TITLE
Bug 1402878 - Add some more sanity-type tests, including perl critic

### PR DESCRIPTION
**Pull request by dylanwh**

### CODE REVIEW

**Comment by dylanwh** [comment]
Because of the nature of this change, it needs review from the other BMO module owner -- @dklawren

**Comment by dklawren** [comment]
@dylanwh any reason that you do not have it named t/013critic.t?

**Comment by dylanwh** [comment]
I had stopped numbering tests as it made merging into upstream more difficult. there's a few other un-numbered ones too, css.t for instance

**Comment by dylanwh** [comment]
@dklawren hoping I can get approval on this today -- anything I can do to help debug that error you had on your env ?

**Pull request merged**
