### PR TITLE
Bug 1527841 - Add ability to search for bugs where assignee or needinfo’d people have last seen gt/lt X

### PR DESCRIPTION
**Pull request by kyoshino**
Add new `assignee_last_seen`, `needinfo` and `needinfo_last_seen` fields to let people search bugs based on assignee or needinfo’d user’s last activity. A typical custom search criteria will be:

* Needinfo / is not empty
* Needinfo Last Seen Date / is less than / -2y

## Bugzilla link

[Bug 1527841 - Add ability to search for bugs where assignee or needinfo’d people have last seen gt/lt X](https://bugzilla.mozilla.org/show_bug.cgi?id=1527841)

### CODE REVIEW

**Comment by kyoshino** [comment]
Need API.

**Comment by emceeaich** [comment]
This will make specifying searches that triage owners need to watch so much easier.

**Comment by kyoshino** [comment]
I’m honestly not sure if this is useful. Active users ignoring needinfos are rather a problem than inactive people never answer questions, eh?

**Comment by kyoshino** [comment]
I was implementing the `needinfo` and `needinfo_detail` fields to `/rest/bug`, but realized that it would overlap with the `flags` and `cc` fields, so just added to `last_activity` to `cc` and other user objects, which will be retuned if the request is authenticated.

**Pull request closed without merging**
